### ISSUE TITLE
Error running md2anki

### ISSUE THREAD

**Issue by Nightwindx** [Mochitto/Markdown2Anki#23]
Hello, 
I am facing an issue after running "md2anki" in PowerShell/CMD/terminal. I have upgraded the software, uninstalled then reinstalled, restarted laptop, uninstalled then reinstalled python, ran PowerShell as Administrator, and added python to PATH before installation. Still did not work.

This is the error: 
Traceback (most recent call last):
  File "C:\Users\jadma\AppData\Local\Programs\Python\Python312\Lib\site-packages\markdown2anki\config\configs_handle.py", line 77, in handle_configs
    config_dir, config_file = get_configfile_paths(config_link_path)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jadma\AppData\Local\Programs\Python\Python312\Lib\site-packages\markdown2anki\config\configs_handle.py", line 26, in get_configfile_paths
    raise FileNotFoundError(
FileNotFoundError: The path to the file containing the link to the config file doesn't exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jadma\AppData\Local\Programs\Python\Python312\Scripts\md2anki.exe\__main__.py", line 7, in <module>
  File "C:\Users\jadma\AppData\Local\Programs\Python\Python312\Lib\site-packages\markdown2anki\__init__.py", line 30, in main
    config = config_handle.handle_configs(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jadma\AppData\Local\Programs\Python\Python312\Lib\site-packages\markdown2anki\config\configs_handle.py", line 79, in handle_configs
    welcome_user(
  File "C:\Users\jadma\AppData\Local\Programs\Python\Python312\Lib\site-packages\markdown2anki\config\first_config.py", line 32, in welcome_user
    welcome_msg = get_welcome_message(
                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jadma\AppData\Local\Programs\Python\Python312\Lib\site-packages\markdown2anki\config\first_config.py", line 95, in get_welcome_message
    welcome_msg = welcome_file.read()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jadma\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1115: character maps to <undefined>

---------------------------------------
Python version: 3.12.1
Edition: Windows 11 Home
Version: 22H2
System type: 64-bit operating system, x64-based processor

**Comment by Mochitto** [comment]
I think this error is due to your terminal not being able to render emojis; could you confirm this? Try installing the [Windows terminal app](https://apps.microsoft.com/detail/9n0dx20hk701?rtc=1&hl=it-it&gl=IT) and running the app using it instead of PowerShell, as powershell doesn't support emojis, which the app uses to give users better feedback on what's happening.

You can read about this in the [Installation](https://github.com/Mochitto/Markdown2Anki?tab=readme-ov-file#installation) step of the README.

Sorry for the inconvenience, let me know if that works for you :)

**Comment by Mochitto** [comment]
Closing due to missing feedback, hopefully solved
